language: swift
osx_image: xcode11.3

before_install:
  - gem install cocoapods -v '1.8.3'
  - pod install

script:
  - xcodebuild -workspace the-moviedb-app.xcworkspace -scheme the-moviedb-appTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.3' test ONLY_ACTIVE_ARCH=NO
